[package]
name = "sample_store"
version = "0.0.1"

[addresses]
std = "0x1"
initia_std = "0x1"
me = "0x2"


[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/testnet.git", subdir = "stone-8/move/initia_stdlib", rev = "0e70b719bf9fd5e10173fa8e56fab2ff640fdcc4"  }
